package Proyecto.T03.Util;

public enum operations {
	SUMA, RESTA, MULTIPLICACION, DIVISION, ELEVACION, RAIZ, // OPERACIONES
	MINIMO, MAXIMO, PROMEDIO, VARIABLE, // OPERACION - FULT
	ASSIGNACION, OBTENCION, // OPERACION - TRATO DE VARIABLES
	NINGUNA;
}
